package org.compiere.production;

import kotliquery.Row;
import org.compiere.model.User;
import org.compiere.model.Workflow;
import org.compiere.orm.PO;
import org.eevolution.model.I_PP_Product_Planning;
import org.idempiere.common.util.Env;
import software.hsharp.core.orm.MBaseTableKt;

import java.math.BigDecimal;

/**
 * Generated Model for PP_Product_Planning
 *
 * @author iDempiere (generated)
 * @version Release 5.1 - $Id$
 */
public class X_PP_Product_Planning extends PO implements I_PP_Product_Planning {

    /**
     * Fixed Order Quantity = FOQ
     */
    public static final String ORDER_POLICY_FixedOrderQuantity = "FOQ";
    /**
     * Lot-for-Lot = LFL
     */
    public static final String ORDER_POLICY_Lot_For_Lot = "LFL";
    /**
     * Period Order Quantity = POQ
     */
    public static final String ORDER_POLICY_PeriodOrderQuantity = "POQ";
    /**
     *
     */
    private static final long serialVersionUID = 20171031L;

    /**
     * Standard Constructor
     */
    public X_PP_Product_Planning(int PP_Product_Planning_ID) {
        super(PP_Product_Planning_ID);
    }


    /**
     * Load Constructor
     */
    public X_PP_Product_Planning(Row row) {
        super(row);
    }

    /**
     * AccessLevel
     *
     * @return 3 - Client - Org
     */
    protected int getAccessLevel() {
        return accessLevel.intValue();
    }

    @Override
    public int getTableId() {
        return Table_ID;
    }

    public String toString() {
        return "X_PP_Product_Planning[" + getId() + "]";
    }

    public Workflow getWorkflow() throws RuntimeException {
        return (Workflow)
                MBaseTableKt.getTable(Workflow.Table_Name)
                        .getPO(getWorkflowId());
    }

    /**
     * Get Workflow.
     *
     * @return Workflow or combination of tasks
     */
    public int getWorkflowId() {
        Integer ii = getValue(COLUMNNAME_AD_Workflow_ID);
        if (ii == null) return 0;
        return ii;
    }

    /**
     * Set Workflow.
     *
     * @param AD_Workflow_ID Workflow or combination of tasks
     */
    public void setWorkflowId(int AD_Workflow_ID) {
        if (AD_Workflow_ID < 1) setValue(COLUMNNAME_AD_Workflow_ID, null);
        else setValue(COLUMNNAME_AD_Workflow_ID, Integer.valueOf(AD_Workflow_ID));
    }

    public org.eevolution.model.I_DD_NetworkDistribution getNetworkDistribution()
            throws RuntimeException {
        return (org.eevolution.model.I_DD_NetworkDistribution)
                MBaseTableKt.getTable(org.eevolution.model.I_DD_NetworkDistribution.Table_Name)
                        .getPO(getNetworkDistributionId());
    }

    /**
     * Get Network Distribution.
     *
     * @return Network Distribution
     */
    public int getNetworkDistributionId() {
        Integer ii = getValue(COLUMNNAME_DD_NetworkDistribution_ID);
        if (ii == null) return 0;
        return ii;
    }

    /**
     * Set Network Distribution.
     *
     * @param DD_NetworkDistribution_ID Network Distribution
     */
    public void setNetworkDistributionId(int DD_NetworkDistribution_ID) {
        if (DD_NetworkDistribution_ID < 1) setValue(COLUMNNAME_DD_NetworkDistribution_ID, null);
        else
            setValue(COLUMNNAME_DD_NetworkDistribution_ID, Integer.valueOf(DD_NetworkDistribution_ID));
    }

    /**
     * Get Promised Delivery Time.
     *
     * @return Promised days between order and delivery
     */
    public BigDecimal getDeliveryTimePromised() {
        BigDecimal bd = getValue(COLUMNNAME_DeliveryTime_Promised);
        if (bd == null) return Env.ZERO;
        return bd;
    }

    /**
     * Set Promised Delivery Time.
     *
     * @param DeliveryTime_Promised Promised days between order and delivery
     */
    public void setDeliveryTimePromised(BigDecimal DeliveryTime_Promised) {
        setValue(COLUMNNAME_DeliveryTime_Promised, DeliveryTime_Promised);
    }

    /**
     * Set Create Plan.
     *
     * @param IsCreatePlan Indicates whether planned orders will be generated by MRP
     */
    public void setIsCreatePlan(boolean IsCreatePlan) {
        setValue(COLUMNNAME_IsCreatePlan, Boolean.valueOf(IsCreatePlan));
    }

    /**
     * Get Create Plan.
     *
     * @return Indicates whether planned orders will be generated by MRP
     */
    public boolean isCreatePlan() {
        Object oo = getValue(COLUMNNAME_IsCreatePlan);
        if (oo != null) {
            if (oo instanceof Boolean) return ((Boolean) oo).booleanValue();
            return "Y".equals(oo);
        }
        return false;
    }

    /**
     * Set Is MPS.
     *
     * @param IsMPS Is MPS
     */
    public void setIsMPS(boolean IsMPS) {
        setValue(COLUMNNAME_IsMPS, Boolean.valueOf(IsMPS));
    }

    /**
     * Get Is MPS.
     *
     * @return Is MPS
     */
    public boolean isMPS() {
        Object oo = getValue(COLUMNNAME_IsMPS);
        if (oo != null) {
            if (oo instanceof Boolean) return ((Boolean) oo).booleanValue();
            return "Y".equals(oo);
        }
        return false;
    }

    /**
     * Set Phantom.
     *
     * @param IsPhantom Phantom Component
     */
    public void setIsPhantom(boolean IsPhantom) {
        setValue(COLUMNNAME_IsPhantom, Boolean.valueOf(IsPhantom));
    }

    /**
     * Get Phantom.
     *
     * @return Phantom Component
     */
    public boolean isPhantom() {
        Object oo = getValue(COLUMNNAME_IsPhantom);
        if (oo != null) {
            if (oo instanceof Boolean) return ((Boolean) oo).booleanValue();
            return "Y".equals(oo);
        }
        return false;
    }

    /**
     * Set Required Calculate DRP.
     *
     * @param IsRequiredDRP Required Calculate DRP
     */
    public void setIsRequiredDRP(boolean IsRequiredDRP) {
        setValueNoCheck(COLUMNNAME_IsRequiredDRP, Boolean.valueOf(IsRequiredDRP));
    }

    /**
     * Get Required Calculate DRP.
     *
     * @return Required Calculate DRP
     */
    public boolean isRequiredDRP() {
        Object oo = getValue(COLUMNNAME_IsRequiredDRP);
        if (oo != null) {
            if (oo instanceof Boolean) return ((Boolean) oo).booleanValue();
            return "Y".equals(oo);
        }
        return false;
    }

    /**
     * Set Required Calculate MRP.
     *
     * @param IsRequiredMRP Required Calculate MRP
     */
    public void setIsRequiredMRP(boolean IsRequiredMRP) {
        setValueNoCheck(COLUMNNAME_IsRequiredMRP, Boolean.valueOf(IsRequiredMRP));
    }

    /**
     * Get Required Calculate MRP.
     *
     * @return Required Calculate MRP
     */
    public boolean isRequiredMRP() {
        Object oo = getValue(COLUMNNAME_IsRequiredMRP);
        if (oo != null) {
            if (oo instanceof Boolean) return ((Boolean) oo).booleanValue();
            return "Y".equals(oo);
        }
        return false;
    }

    public org.compiere.model.I_M_Product getProduct() throws RuntimeException {
        return (org.compiere.model.I_M_Product)
                MBaseTableKt.getTable(org.compiere.model.I_M_Product.Table_Name)
                        .getPO(getProductId());
    }

    /**
     * Get Product.
     *
     * @return Product, Service, Item
     */
    public int getProductId() {
        Integer ii = getValue(COLUMNNAME_M_Product_ID);
        if (ii == null) return 0;
        return ii;
    }

    /**
     * Set Product.
     *
     * @param M_Product_ID Product, Service, Item
     */
    public void setProductId(int M_Product_ID) {
        if (M_Product_ID < 1) setValueNoCheck(COLUMNNAME_M_Product_ID, null);
        else setValueNoCheck(COLUMNNAME_M_Product_ID, Integer.valueOf(M_Product_ID));
    }

    public org.compiere.model.I_M_Warehouse getWarehouse() throws RuntimeException {
        return (org.compiere.model.I_M_Warehouse)
                MBaseTableKt.getTable(org.compiere.model.I_M_Warehouse.Table_Name)
                        .getPO(getWarehouseId());
    }

    /**
     * Get Warehouse.
     *
     * @return Storage Warehouse and Service Point
     */
    public int getWarehouseId() {
        Integer ii = getValue(COLUMNNAME_M_Warehouse_ID);
        if (ii == null) return 0;
        return ii;
    }

    /**
     * Set Warehouse.
     *
     * @param M_Warehouse_ID Storage Warehouse and Service Point
     */
    public void setWarehouseId(int M_Warehouse_ID) {
        if (M_Warehouse_ID < 1) setValue(COLUMNNAME_M_Warehouse_ID, null);
        else setValue(COLUMNNAME_M_Warehouse_ID, Integer.valueOf(M_Warehouse_ID));
    }

    /**
     * Get Maximum Order Qty.
     *
     * @return Maximum order quantity in UOM
     */
    public BigDecimal getOrderMax() {
        BigDecimal bd = getValue(COLUMNNAME_Order_Max);
        if (bd == null) return Env.ZERO;
        return bd;
    }

    /**
     * Set Maximum Order Qty.
     *
     * @param Order_Max Maximum order quantity in UOM
     */
    public void setOrderMax(BigDecimal Order_Max) {
        setValue(COLUMNNAME_Order_Max, Order_Max);
    }

    /**
     * Get Minimum Order Qty.
     *
     * @return Minimum order quantity in UOM
     */
    public BigDecimal getOrderMin() {
        BigDecimal bd = getValue(COLUMNNAME_Order_Min);
        if (bd == null) return Env.ZERO;
        return bd;
    }

    /**
     * Set Minimum Order Qty.
     *
     * @param Order_Min Minimum order quantity in UOM
     */
    public void setOrderMin(BigDecimal Order_Min) {
        setValue(COLUMNNAME_Order_Min, Order_Min);
    }

    /**
     * Get Order Pack Qty.
     *
     * @return Package order size in UOM (e.g. order set of 5 units)
     */
    public BigDecimal getOrderPack() {
        BigDecimal bd = getValue(COLUMNNAME_Order_Pack);
        if (bd == null) return Env.ZERO;
        return bd;
    }

    /**
     * Set Order Pack Qty.
     *
     * @param Order_Pack Package order size in UOM (e.g. order set of 5 units)
     */
    public void setOrderPack(BigDecimal Order_Pack) {
        setValue(COLUMNNAME_Order_Pack, Order_Pack);
    }

    /**
     * Get Order Period.
     *
     * @return Order Period
     */
    public BigDecimal getOrderPeriod() {
        BigDecimal bd = getValue(COLUMNNAME_Order_Period);
        if (bd == null) return Env.ZERO;
        return bd;
    }

    /**
     * Set Order Period.
     *
     * @param Order_Period Order Period
     */
    public void setOrderPeriod(BigDecimal Order_Period) {
        setValue(COLUMNNAME_Order_Period, Order_Period);
    }

    /**
     * Get Order Policy.
     *
     * @return Order Policy
     */
    public String getOrderPolicy() {
        return getValue(COLUMNNAME_Order_Policy);
    }

    /**
     * Set Order Policy.
     *
     * @param Order_Policy Order Policy
     */
    public void setOrderPolicy(String Order_Policy) {

        setValue(COLUMNNAME_Order_Policy, Order_Policy);
    }

    /**
     * Get Order Qty.
     *
     * @return Order Qty
     */
    public BigDecimal getOrderQty() {
        BigDecimal bd = getValue(COLUMNNAME_Order_Qty);
        if (bd == null) return Env.ZERO;
        return bd;
    }

    /**
     * Set Order Qty.
     *
     * @param Order_Qty Order Qty
     */
    public void setOrderQty(BigDecimal Order_Qty) {
        setValue(COLUMNNAME_Order_Qty, Order_Qty);
    }

    public User getPlanner() throws RuntimeException {
        return (User)
                MBaseTableKt.getTable(User.Table_Name)
                        .getPO(getPlannerId());
    }

    /**
     * Get Planner.
     *
     * @return Planner
     */
    public int getPlannerId() {
        Integer ii = getValue(COLUMNNAME_Planner_ID);
        if (ii == null) return 0;
        return ii;
    }

    /**
     * Set Planner.
     *
     * @param Planner_ID Planner
     */
    public void setPlannerId(int Planner_ID) {
        if (Planner_ID < 1) setValue(COLUMNNAME_Planner_ID, null);
        else setValue(COLUMNNAME_Planner_ID, Integer.valueOf(Planner_ID));
    }

    public org.eevolution.model.I_PP_Product_BOM getProductBOM() throws RuntimeException {
        return (org.eevolution.model.I_PP_Product_BOM)
                MBaseTableKt.getTable(org.eevolution.model.I_PP_Product_BOM.Table_Name)
                        .getPO(getProductBOMId());
    }

    /**
     * Get BOM & Formula.
     *
     * @return BOM & Formula
     */
    public int getProductBOMId() {
        Integer ii = getValue(COLUMNNAME_PP_Product_BOM_ID);
        if (ii == null) return 0;
        return ii;
    }

    /**
     * Set BOM & Formula.
     *
     * @param PP_Product_BOM_ID BOM & Formula
     */
    public void setProductBOMId(int PP_Product_BOM_ID) {
        if (PP_Product_BOM_ID < 1) setValue(COLUMNNAME_PP_Product_BOM_ID, null);
        else setValue(COLUMNNAME_PP_Product_BOM_ID, Integer.valueOf(PP_Product_BOM_ID));
    }

    /**
     * Get Product Planning.
     *
     * @return Product Planning
     */
    public int getProductPlanningId() {
        Integer ii = getValue(COLUMNNAME_PP_Product_Planning_ID);
        if (ii == null) return 0;
        return ii;
    }

    /**
     * Set Product Planning.
     *
     * @param PP_Product_Planning_ID Product Planning
     */
    public void setProductPlanningId(int PP_Product_Planning_ID) {
        if (PP_Product_Planning_ID < 1) setValueNoCheck(COLUMNNAME_PP_Product_Planning_ID, null);
        else
            setValueNoCheck(COLUMNNAME_PP_Product_Planning_ID, Integer.valueOf(PP_Product_Planning_ID));
    }

    /**
     * Get PP_Product_Planning_UU.
     *
     * @return PP_Product_Planning_UU
     */
    public String getProduct_Planning_UU() {
        return getValue(COLUMNNAME_PP_Product_Planning_UU);
    }

    /**
     * Set PP_Product_Planning_UU.
     *
     * @param PP_Product_Planning_UU PP_Product_Planning_UU
     */
    public void setProduct_Planning_UU(String PP_Product_Planning_UU) {
        setValue(COLUMNNAME_PP_Product_Planning_UU, PP_Product_Planning_UU);
    }

    /**
     * Get Safety Stock Qty.
     *
     * @return Safety stock is a term used to describe a level of stock that is maintained below the
     * cycle stock to buffer against stock-outs
     */
    public BigDecimal getSafetyStock() {
        BigDecimal bd = getValue(COLUMNNAME_SafetyStock);
        if (bd == null) return Env.ZERO;
        return bd;
    }

    /**
     * Set Safety Stock Qty.
     *
     * @param SafetyStock Safety stock is a term used to describe a level of stock that is maintained
     *                    below the cycle stock to buffer against stock-outs
     */
    public void setSafetyStock(BigDecimal SafetyStock) {
        setValue(COLUMNNAME_SafetyStock, SafetyStock);
    }

    public org.compiere.model.I_S_Resource getResource() throws RuntimeException {
        return (org.compiere.model.I_S_Resource)
                MBaseTableKt.getTable(org.compiere.model.I_S_Resource.Table_Name)
                        .getPO(getResourceID());
    }

    /**
     * Get Resource.
     *
     * @return Resource
     */
    public int getResourceID() {
        Integer ii = getValue(COLUMNNAME_S_Resource_ID);
        if (ii == null) return 0;
        return ii;
    }

    /**
     * Set Resource.
     *
     * @param S_Resource_ID Resource
     */
    public void setResourceID(int S_Resource_ID) {
        if (S_Resource_ID < 1) setValueNoCheck(COLUMNNAME_S_Resource_ID, null);
        else setValueNoCheck(COLUMNNAME_S_Resource_ID, S_Resource_ID);
    }

    /**
     * Get Time Fence.
     *
     * @return Time Fence
     */
    public BigDecimal getTimeFence() {
        BigDecimal bd = getValue(COLUMNNAME_TimeFence);
        if (bd == null) return Env.ZERO;
        return bd;
    }

    /**
     * Set Time Fence.
     *
     * @param TimeFence Time Fence
     */
    public void setTimeFence(BigDecimal TimeFence) {
        setValue(COLUMNNAME_TimeFence, TimeFence);
    }

    /**
     * Get Transfert Time.
     *
     * @return Transfert Time
     */
    public BigDecimal getTransfertTime() {
        BigDecimal bd = getValue(COLUMNNAME_TransfertTime);
        if (bd == null) return Env.ZERO;
        return bd;
    }

    /**
     * Set Transfert Time.
     *
     * @param TransfertTime Transfert Time
     */
    public void setTransfertTime(BigDecimal TransfertTime) {
        setValue(COLUMNNAME_TransfertTime, TransfertTime);
    }

    /**
     * Get Working Time.
     *
     * @return Workflow Simulation Execution Time
     */
    public BigDecimal getWorkingTime() {
        BigDecimal bd = getValue(COLUMNNAME_WorkingTime);
        if (bd == null) return Env.ZERO;
        return bd;
    }

    /**
     * Set Working Time.
     *
     * @param WorkingTime Workflow Simulation Execution Time
     */
    public void setWorkingTime(BigDecimal WorkingTime) {
        setValue(COLUMNNAME_WorkingTime, WorkingTime);
    }

    /**
     * Get Yield %.
     *
     * @return The Yield is the percentage of a lot that is expected to be of acceptable wuality may
     * fall below 100 percent
     */
    public int getYield() {
        Integer ii = getValue(COLUMNNAME_Yield);
        if (ii == null) return 0;
        return ii;
    }

    /**
     * Set Yield %.
     *
     * @param Yield The Yield is the percentage of a lot that is expected to be of acceptable wuality
     *              may fall below 100 percent
     */
    public void setYield(int Yield) {
        setValue(COLUMNNAME_Yield, Integer.valueOf(Yield));
    }
}
