package org.compiere.invoicing;

import org.compiere.accounting.MStorageOnHand;
import org.compiere.model.I_M_Inventory;
import org.compiere.model.I_M_InventoryLine;
import org.compiere.model.I_M_InventoryLineMA;
import org.compiere.orm.Query;
import org.idempiere.common.util.CLogger;
import org.idempiere.common.util.Env;
import org.idempiere.common.util.Util;

import java.math.BigDecimal;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.Properties;
import java.util.logging.Level;

import static software.hsharp.core.util.DBKt.*;

/**
 * Inventory Material Allocation
 *
 * @author Jorg Janke
 * @version $Id: MInventoryLineMA.java,v 1.3 2006/07/30 00:51:04 jjanke Exp $
 */
public class MInventoryLineMA extends X_M_InventoryLineMA {
  /** */
  private static final long serialVersionUID = -5654504108476140057L;

  /**
   * Get Material Allocations for Line
   *
   * @param ctx context
   * @param M_InventoryLine_ID line
   * @param trxName trx
   * @return allocations
   */
  public static MInventoryLineMA[] get(Properties ctx, int M_InventoryLine_ID, String trxName) {
    ArrayList<MInventoryLineMA> list = new ArrayList<MInventoryLineMA>();
    String sql = "SELECT * FROM M_InventoryLineMA WHERE M_InventoryLine_ID=?";
    PreparedStatement pstmt = null;
    ResultSet rs = null;
    try {
      pstmt = prepareStatement(sql);
      pstmt.setInt(1, M_InventoryLine_ID);
      rs = pstmt.executeQuery();
      while (rs.next()) list.add(new MInventoryLineMA(ctx, rs, trxName));
    } catch (Exception e) {
      s_log.log(Level.SEVERE, sql, e);
    } finally {

      rs = null;
      pstmt = null;
    }

    MInventoryLineMA[] retValue = new MInventoryLineMA[list.size()];
    list.toArray(retValue);
    return retValue;
  } //	get

  /**
   * Delete all Material Allocation for Inventory
   *
   * @param M_Inventory_ID inventory
   * @param trxName transaction
   * @return number of rows deleted or -1 for error
   */
  public static int deleteInventoryMA(int M_Inventory_ID, String trxName) {
    StringBuilder sql =
        new StringBuilder("DELETE FROM M_InventoryLineMA ma WHERE EXISTS ")
            .append(
                "(SELECT * FROM M_InventoryLine l WHERE l.M_InventoryLine_ID=ma.M_InventoryLine_ID")
            .append(" AND M_Inventory_ID=")
            .append(M_Inventory_ID)
            .append(")");
    return executeUpdate(sql.toString());
  } //	deleteInventoryMA

  /**
   * Delete all Material Allocation for Inventory
   *
   * @param M_InventoryLine_ID inventory
   * @param trxName transaction
   * @return number of rows deleted or -1 for error
   */
  public static int deleteInventoryLineMA(int M_InventoryLine_ID, String trxName) {
    StringBuilder sql =
        new StringBuilder("DELETE FROM M_InventoryLineMA ma WHERE EXISTS ")
            .append(
                "(SELECT * FROM M_InventoryLine l WHERE l.M_InventoryLine_ID=ma.M_InventoryLine_ID")
            .append(" AND M_InventoryLine_ID=")
            .append(M_InventoryLine_ID)
            .append(") AND ma.IsAutoGenerated='Y'");
    return executeUpdate(sql.toString());
  } //	deleteInventoryMA

  /** Logger */
  private static CLogger s_log = CLogger.getCLogger(MInventoryLineMA.class);

  /**
   * ************************************************************************ Standard Constructor
   *
   * @param ctx context
   * @param M_InventoryLineMA_ID ignored
   * @param trxName trx
   */
  public MInventoryLineMA(Properties ctx, int M_InventoryLineMA_ID, String trxName) {
    super(ctx, M_InventoryLineMA_ID, trxName);
    if (M_InventoryLineMA_ID != 0) throw new IllegalArgumentException("Multi-Key");
  } //	MInventoryLineMA

  /**
   * Load Cosntructor
   *
   * @param ctx context
   * @param rs result set
   * @param trxName trx
   */
  public MInventoryLineMA(Properties ctx, ResultSet rs, String trxName) {
    super(ctx, rs, trxName);
  } //	MInventoryLineMA

  /**
   * Parent Constructor
   *
   * @param parent parent
   * @param M_AttributeSetInstance_ID asi
   * @param MovementQty qty
   * @param DateMaterialPolicy
   */
  public MInventoryLineMA(
      MInventoryLine parent,
      int M_AttributeSetInstance_ID,
      BigDecimal MovementQty,
      Timestamp DateMaterialPolicy) {
    this(parent, M_AttributeSetInstance_ID, MovementQty, DateMaterialPolicy, true);
  }

  /**
   * @param parent
   * @param M_AttributeSetInstance_ID
   * @param MovementQty
   * @param DateMaterialPolicy
   * @param isAutoGenerated
   */
  public MInventoryLineMA(
      MInventoryLine parent,
      int M_AttributeSetInstance_ID,
      BigDecimal MovementQty,
      Timestamp DateMaterialPolicy,
      boolean isAutoGenerated) {
    this(parent.getCtx(), 0, null);
    setClientOrg(parent);
    setM_InventoryLine_ID(parent.getM_InventoryLine_ID());
    //
    setM_AttributeSetInstance_ID(M_AttributeSetInstance_ID);
    setMovementQty(MovementQty);
    if (DateMaterialPolicy == null) {
      if (M_AttributeSetInstance_ID > 0) {
        DateMaterialPolicy =
            MStorageOnHand.getDateMaterialPolicy(
                parent.getM_Product_ID(), M_AttributeSetInstance_ID, null);
      }
      if (DateMaterialPolicy == null) {
        DateMaterialPolicy = parent.getParent().getMovementDate();
      }
    }
    setDateMaterialPolicy(DateMaterialPolicy);
    setIsAutoGenerated(isAutoGenerated);
  } //	MInventoryLineMA

  @Override
  public void setDateMaterialPolicy(Timestamp DateMaterialPolicy) {
    if (DateMaterialPolicy != null) DateMaterialPolicy = Util.removeTime(DateMaterialPolicy);
    super.setDateMaterialPolicy(DateMaterialPolicy);
  }

  /**
   * String Representation
   *
   * @return info
   */
  public String toString() {
    StringBuilder sb = new StringBuilder("MInventoryLineMA[");
    sb.append("M_InventoryLine_ID=")
        .append(getM_InventoryLine_ID())
        .append(",M_AttributeSetInstance_ID=")
        .append(getMAttributeSetInstance_ID())
        .append(", Qty=")
        .append(getMovementQty())
        .append("]");
    return sb.toString();
  } //	toString

    public static MInventoryLineMA addOrCreate(
      MInventoryLine line,
      int M_AttributeSetInstance_ID,
      BigDecimal MovementQty,
      Timestamp DateMaterialPolicy,
      boolean isAutoGenerated) {
    Query query =
        new Query(
            Env.getCtx(),
            I_M_InventoryLineMA.Table_Name,
            "M_InventoryLine_ID=? AND M_AttributeSetInstance_ID=? AND DateMaterialPolicy=trunc(cast(? as date))",
            null);
    MInventoryLineMA po =
        query
            .setParameters(
                line.getM_InventoryLine_ID(), M_AttributeSetInstance_ID, DateMaterialPolicy)
            .first();
    if (po == null)
      po =
          new MInventoryLineMA(
              line, M_AttributeSetInstance_ID, MovementQty, DateMaterialPolicy, isAutoGenerated);
    else po.setMovementQty(po.getMovementQty().add(MovementQty));
    return po;
  }

  /**
   * @param M_MovementLine_ID
   * @param trxName
   * @return
   */
  public static BigDecimal getManualQty(int M_MovementLine_ID, String trxName) {
    String sql =
        "SELECT SUM(movementqty) FROM M_InventoryLineMA ma WHERE ma.M_InventoryLine_ID=? AND IsAutoGenerated='N'";
    BigDecimal totalQty = getSQLValueBD(sql, M_MovementLine_ID);
    return totalQty == null ? Env.ZERO : totalQty.negate();
  } // totalLineQty

  /**
   * ************************************************************************ Before Save
   *
   * @param newRecord new
   * @return save
   */
  protected boolean beforeSave(boolean newRecord) {
    // Set DateMaterialPolicy
    if (!newRecord && is_ValueChanged(I_M_InventoryLineMA.COLUMNNAME_M_AttributeSetInstance_ID)) {
      I_M_InventoryLine line = getM_InventoryLine();

      Timestamp dateMPolicy = null;
      if (getMAttributeSetInstance_ID() > 0) {
        dateMPolicy =
            MStorageOnHand.getDateMaterialPolicy(
                line.getM_Product_ID(), getMAttributeSetInstance_ID(), null);
      }

      if (dateMPolicy == null) {
        I_M_Inventory inventory = line.getM_Inventory();
        dateMPolicy = inventory.getMovementDate();
      }

      setDateMaterialPolicy(dateMPolicy);
    }

    return true;
  } // beforeSave
} //	MInventoryLineMA
